micronaut:
  application:
    name: TODO_App
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
datasources:
  default:
    url: jdbc:mysql://localhost:3306/Todo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'logic123'
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
